station_entries = [
    {'label': 'Station 11', 'value': 11},
    #{'label': 'Station 12', 'value': 12},
    #{'label': 'Station 13', 'value': 13},
    #{'label': 'Station 14', 'value': 14},
    {'label': 'Station 21', 'value': 21},
    {'label': 'Station 22', 'value': 22},
    #{'label': 'Station 23', 'value': 23},
    #{'label': 'Station 24', 'value': 24},
    #{'label': 'Station 25', 'value': 25},
    {'label': 'Station not set', 'value': 0},
    {'label': 'Fake Station', 'value': 12345}
]

channel_entries = [
    {'label': 'Ch. 0 (PA)', 'value': 0},
    {'label': 'Ch. 1 (PA)', 'value': 1},
    {'label': 'Ch. 2 (PA)', 'value': 2},
    {'label': 'Ch. 3 (PA)', 'value': 3},
    {'label': 'Ch. 4 (PS Hpol)', 'value': 4},
    {'label': 'Ch. 5 (PS Hpol)', 'value': 5},
    {'label': 'Ch. 6 (PS Vpol)', 'value': 6},
    {'label': 'Ch. 7 (PS Vpol)', 'value': 7},
    {'label': 'Ch. 8 (PS Vpol)', 'value': 8},
    {'label': 'Ch. 9 (HS B Vpol)', 'value': 9},
    {'label': 'Ch. 10 (HS B Vpol)', 'value': 10},
    {'label': 'Ch. 11 (HS B Hpol)', 'value': 11},
    {'label': 'Ch. 12 (Surf. Arm A)', 'value': 12},
    {'label': 'Ch. 13 (Surf. Arm A)', 'value': 13},
    {'label': 'Ch. 14 (Surf. Arm A)', 'value': 14},
    {'label': 'Ch. 15 (Surf. Arm B)', 'value': 15},
    {'label': 'Ch. 16 (Surf. Arm B)', 'value': 16},
    {'label': 'Ch. 17 (Surf. Arm B)', 'value': 17},
    {'label': 'Ch. 18 (Surf. Arm C)', 'value': 18},
    {'label': 'Ch. 19 (Surf. Arm C)', 'value': 19},
    {'label': 'Ch. 20 (Surf. Arm C)', 'value': 20},
    {'label': 'Ch. 21 (HS A Vpol)', 'value': 21},
    {'label': 'Ch. 22 (HS A Vpol)', 'value': 22},
    {'label': 'Ch. 23 (HS A Hpol)', 'value': 23},
]
